image:
  repository: ghcr.io/opentdf/keycloak
  # Keycloak is a non-OpenTDF chart, but with an OpenTDF image
  tag: sha-0b804dd
postgresql:
  enabled: false
  postgresqlUsername: postgres
  postgresqlPassword: mydbapassword
  postgresqlDatabase: keycloak_database
externalDatabase:
  host: opentdf-postgresql
  user: postgres
  password: mydbapassword
  database: keycloak_database
extraEnv: |
  - name: CLAIMS_URL
    value: http://claims:5000/claims
# - name: DB_VENDOR
#   value: postgres
# - name: DB_ADDR
#   value: postgresql
# - name: DB_DATABASE
#   value: keycloak_database
# - name: DB_PORT
#   value: "5432"
# - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
#   value: "true"
# - name: KEYCLOAK_FRONTEND_URL
#   value: "http://offline.demo.internal/auth"
# - name: KEYCLOAK_LOG_LEVEL
#   value: DEBUG
extraEnvFrom: |
  - secretRef:
      name: 'keycloak-secrets'
ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: localhost
      paths: &paths
        - path: /auth(/|$)(.*)
          pathType: Prefix
    - host: host.docker.internal
      paths: *paths
    - host: offline.demo.internal
      paths: *paths
    - host: opentdf.local
      paths: *paths
  tls: null
