endpoints:
  easHost: http://attributes:4020
  oidcPubkeyEndpoint: http://keycloak-http
image:
  image: ghcr.io/opentdf/kas:main
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: nginx
  hosts:
    localhost: &paths
      "/api/kas(/|$)(.*)":
        pathType: Prefix
    host.docker.internal: *paths
secretRef:
 name: kas-secrets
